server:
  port: ${PORT:8080}
telegram:
  bot:
    hbj:
      name: ${BOT_NAME}
      token: ${BOT_TOKEN}
      media-path: ${MEDIA_PATH}
      journey-load-file: ${JOURNEY_LOAD_FILE}
    hbj-admin:
      name: ${ADMIN_BOT_NAME}
      token: ${ADMIN_BOT_TOKEN}
      chat: ${ADMIN_CHAT}
save:
  path: /home/viktorvx/Загрузки/hbj/save/
  enabled: true