server:
  port: ${PORT:8080}
telegram:
  bot:
    hbj:
      name: ${BOT_NAME}
      token: ${BOT_TOKEN}
      media-path: /home/viktorvx/Загрузки/hbj/
save:
  path: /home/viktorvx/Загрузки/hbj/save/
  enabled: true